### ISSUE TITLE
Crashing Neovim when running `ff` after latest updates

### ISSUE THREAD

**Issue by nickkadutskyi** [dmtrKovalenko/fff.nvim#196]
When I run `ff` or `:lua require('fff').find_files()` Neovim exits after latest updates. 
I installed using `nix` by running `nix run .#release`, also tried `require("fff.download").download_or_build_binary()`.

It works on e3f788f and 003c05cf

MacOS 26.1
Neovim v0.11.5

**Comment by aaronmcadam** [comment]
Since the last few commits, every time `fff` updates, Neovim crashes and exits when I restart it. It continues crashing on startup until I clear the Neovim state with `rm -rf ~/.local/share/nvim/` and reinstall all plugins.

**Comment by AlejandroSanchez90** [comment]
im getting error on launch afdter the update Error: No valid library found in any search path

its building correctly but still getting this

edit: had to install nightly, because some dependencies were throwing on build...

**Comment by aaronmcadam** [comment]
> im getting error on launch afdter the update Error: No valid library found in any search path

I'm seeing the same now.

**Comment by nickkadutskyi** [comment]
I am having the same issue on d997344fd70c0396f6097b344ef868c4e2913bad if I use:
```lua
build = function()
    -- this will download prebuild binary or try to use existing rustup toolchain to build from source
    -- (if you are using lazy you can use gb for rebuilding a plugin if needed)
    require("fff.download").download_or_build_binary()
end,
```
I am on MacOS so my guess is that it just didn't download the binary for my system and I don't have rust tooling in the path so it didn't build it. 
But I use nix so I ran `nix run .\#release` in lazy dir for fff.nvim repo and it works now.

**Comment by eokoshi** [comment]
After recent update, probably something to do with commit a4f87bd, fff did not properly install. 
Solved by rm -rf .local/share/nvim/lazy/fff.nvim and reinstalling from scratch (just opening nvim and letting lazy take care of it)

```
Error executing vim.schedule lua callback: .../user/.local/share/nvim/lazy/fff.nvim/lua/fff/fuzzy.lua:6: Failed to load fff.rust module: ...an/.local/share/nvim/lazy/fff.nvim/lua/fff/rust/init.lua:53: Failed to load fff rust backend.
Error: No valid library found in any search path
Searched paths:
{ "/home/user/.local/share/nvim/lazy/fff.nvim/lua/../target/release/lib?.so", "/home/user/.local/share/nvim/lazy/fff.nvim/lua/fff/rust/../../../target/release/lib?.so", "/home/user/.local/share/nvim/lazy/fff.nvim/lua/fff/rust/../../../target/release/?.so" }
Make sure binary exists with `cargo build --release`
stack traceback:
	[C]: in function 'error'
	.../user/.local/share/nvim/lazy/fff.nvim/lua/fff/fuzzy.lua:6: in main chunk
	[C]: in function 'require'
	...e/user/.local/share/nvim/lazy/fff.nvim/lua/fff/core.lua:1: in main chunk
	[C]: in function 'require'
	/home/user/.local/share/nvim/lazy/fff.nvim/plugin/fff.lua:11: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by nickkadutskyi** [comment]
@dmtrKovalenko 
When running `lua require("fff.download").download_or_build_binary()` I am getting this error after update to b384bf7dada21e1d8c533aec5b2e04f75cc05131 
```
Error executing callback:
...ick/.local/share/nvim/lazy/fff.nvim/lua/fff/download.lua:35: attempt to call global 'mkdir_recursive' (a nil value)
stack traceback:
        ...ick/.local/share/nvim/lazy/fff.nvim/lua/fff/download.lua:35: in function 'download_file'
        ...ick/.local/share/nvim/lazy/fff.nvim/lua/fff/download.lua:79: in function 'download_from_github'
        ...ick/.local/share/nvim/lazy/fff.nvim/lua/fff/download.lua:118: in function 'callback'
        ...ick/.local/share/nvim/lazy/fff.nvim/lua/fff/download.lua:12: in function 'on_exit'
        ...-unwrapped-0.11.5/share/nvim/runtime/lua/vim/_system.lua:318: in function <...-unwrapped-0.11.5/share/nvim/runtime/lua/vim/_system.lua:288>
```

**Comment by dmtrKovalenko** [comment]
Shit

**Comment by dmtrKovalenko** [comment]
should be actually fixed by now sorry that was a long day lol I need more tests for varios scripts

**Comment by nickkadutskyi** [comment]
It works, thank you!

**Comment by dlvhdr** [comment]
This is still happening to me, how do I fix it?
Running `lua require("fff.download").download_or_build_binary()` crashes nvim.

Update: I *think* I sorted this out. Some update changed the last param to the find files function I was using. It should now be nil and not false. I don't know if this really has something to do with it.

**Comment by dlvhdr** [comment]
Seems like I still need to be running `rm -rf ~/.local/share/nvim/lazy/fff.nvim` after every update to fff.nvim

**Comment by dmtrKovalenko** [comment]
Wow fff didn't have update for a while maybe you run the same update
