### ISSUE TITLE
[nixvim] fff.nvim fails to build with an extraPlugin

### ISSUE THREAD

**Issue by Sipepper** [dmtrKovalenko/fff.nvim#67]
I'm using neovim through the [NixVim](https://github.com/nix-community/nixvim). And by noticing that fff has a flake.nix I tried to pass it directly to my NixOS config flake as an input and use it via nixvim.extraPlugins in the following way:
```nix
inputs = {
  nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
  determinate.url = "https://flakehub.com/f/DeterminateSystems/determinate/*";

  home-manager = {
    url = "github:nix-community/home-manager";
    inputs.nixpkgs.follows = "nixpkgs";
  };

  nixvim = {
    url = "github:nix-community/nixvim";
    inputs.nixpkgs.follows = "nixpkgs";
  };

  fff-nvim = {
    url = "github:dmtrKovalenko/fff.nvim";
    inputs.nixpkgs.follows = "nixpkgs";
  };
};
```
and
```nix
extraPlugins = [
  (pkgs.vimUtils.buildVimPlugin{
    name = "fff.nvim";
    src = inputs.fff-nvim;
  })
];
``` 

but system fails to build at:
```
error: Cannot build '/nix/store/pzxb9j1f15cd7krp9paqz8cyzj2g82mx-vimplugin-fff.nvim.drv'.
       Reason: builder failed with exit code 1.
       Output paths:
         /nix/store/nwvacqy05z4d7icz2vwvrkwgw5rizdn0-vimplugin-fff.nvim
       Last 25 log lines:
       > E5113: Error while calling lua chunk: ...4d7icz2vwvrkwgw5rizdn0-vimplugin-fff.nvim/plugin/fff.lua:1: loop or previous err
or loading module 'fff.main'
       > stack traceback:
       >     [C]: in function 'require'
       >      ...4d7icz2vwvrkwgw5rizdn0-vimplugin-fff.nvim/plugin/fff.lua:1: in main chunk
       > Entering Ex mode.  Type "visual" to go to Normal mode.
       > :Failed to require module: fff.rust.init
       >
       > ======================================================
       > No successful require checks.
       >
       > Require check failed for the following modules:
       >   - fff
       >   - fff.main
       >   - fff.picker_ui
       >   - fff.file_picker.init
       >   - fff.file_picker.preview
       >   - fff.file_picker.icons
       >   - fff.file_picker.image
       >   - fff.fuzzy
       >   - fff.git_utils
       >   - fff.utils
       >   - fff.rust.init
       >
       > Checkout https://nixos.org/manual/nixpkgs/unstable/#testing-neovim-plugins-neovim-require-check
       > ======================================================
       For full logs, run:
         nix log /nix/store/pzxb9j1f15cd7krp9paqz8cyzj2g82mx-vimplugin-fff.nvim.drv
error: Cannot build '/nix/store/f89w00lx3ygajh3fk7f3hal3l9hfmfan-vimplugin-plugin-pack.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/44vq903d6gxxniy2n4nimksl60bfxfap-vimplugin-plugin-pack
error: Cannot build '/nix/store/48g1jdlnja3dgl2aaf36g7341z9qy1f7-neovim-0.11.3.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/h7qfmxc8jwyxw3n0x8nkpyk2ky8ygza5-neovim-0.11.3
error: Cannot build '/nix/store/051v8amq8iy75p5q6rimfxs26k54r72l-nixvim.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/4dapjxya4s1ix09272869vr3kcpgqjr6-nixvim
error: Cannot build '/nix/store/nn100cc05w6dg04mh5ip25dp2ycldxs3-home-manager-path.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/ymk65nskm9vbky9cl7k0lrr8nw037jjy-home-manager-path
error: Cannot build '/nix/store/kmf056jw9wz7c86dnk9jg4sijfiqdmni-home-manager-generation.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/0m4lqkfy1glmfysb9vj39fkqmwawkxkn-home-manager-generation
error: Cannot build '/nix/store/npkahm1mfyw9pmj32ln5jklgpwx4vs8s-unit-home-manager-mlys.service.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/35vl206j92vm3q5shzsy1bfnn9c9fhbn-unit-home-manager-mlys.service
error: Cannot build '/nix/store/3d2wmi47cf350xklkcqzm9798zds656r-system-units.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/yrqb1295qdf946ngwi4ffxfjkxz3h11i-system-units
error: Cannot build '/nix/store/jfkpbj8l551q5jrb5daka2fsmb9pjzyk-etc.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/biwyq6dlgyswffqx07q3lg2sp9lb3ppj-etc
error: Cannot build '/nix/store/p0i2kyv54ss5ijbgc0rk8w2xk4cpnnsh-nixos-system-nixos-25.11.20250719.c87b95e.drv'.
       Reason: 1 dependency failed.
       Output paths:
         /nix/store/a1xsskis7gdv7z2v93ixrwgylankaafy-nixos-system-nixos-25.11.20250719.c87b95e
Command 'nix --extra-experimental-features 'nix-command flakes' build --print-out-paths '/home/mlys/Git/mlys_flake#nixosConfigurat
ions."default".config.system.build.toplevel' --no-link' returned non-zero exit status 1.
```

**Comment by jla2000** [comment]
Should be fixed with https://github.com/dmtrKovalenko/fff.nvim/pull/101
There is now a new flake output `fff-nvim` that can be included.

**Comment by Sipepper** [comment]
Maybe I'm to dumb but I still can't figure out how to use fff-nvim with nixvim. I have checked your (@jla2000 ) repo but due to my NSI( Nix Skill Issues) I couldn't manage to make it work. If someone have a spare half-an-hour can you provide a minimal working example of nixvim configuration which would include the fff? 

p.s. my attempt above now produce fewer failed checks for modules, to be precise:

```
Require check succeeded for the following modules:
- fff
- fff.main
- fff.utils.system
- fff.file_picker.icons
- fff.file_picker.image
- fff.conf
- fff.download
- fff.git_utils
- fff.utils
All lua modules were checked.

Require check failed for the following modules:[0m
- fff.core
- fff.picker_ui
- fff.file_picker.init
- fff.file_picker.preview
- fff.fuzzy
- fff.rust.init
```

Here is the full log.
[fff_log.md](https://github.com/user-attachments/files/22568167/fff_log.md)

**Comment by dmtrKovalenko** [comment]
should be fixed
